### PR TITLE
v1.0.10

### PR DESCRIPTION
**Pull request by yotamloe**
Improve `nodejs` instrumentation:
  - Use `BatchSpanProcessor`
  - Disable `@opentelemetry/instrumentation-fs` To improve performance and avoid high memory usage on startup (https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1344)

### CODE REVIEW

**Comment by yotamloe** [comment]
I'm still considering an option to add `requireParentSpan: true` to the `instrumentation-fs` module to prevent high load of spans

**Comment by mirii1994** [comment]
> I'm still considering an option to add `requireParentSpan: true` to the `instrumentation-fs` module to prevent high load of spans

@yotamloe can we make both requireParentSpan and @opentelemetry/instrumentation-fs configurable? That way we'll have more flexibility to play with those params.

**Comment by yotamloe** [comment]
> > I'm still considering an option to add `requireParentSpan: true` to the `instrumentation-fs` module to prevent high load of spans
> 
> @yotamloe can we make both requireParentSpan and @opentelemetry/instrumentation-fs configurable? That way we'll have more flexibility to play with those params.

The js instrumentation does not offer an easy way to configure it https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/ In general it can be possible but will include some ugly `else` `if` statements in the instrumentation script.. and it will get worse if we will add more stuff like that in the future

**Review by mirii1994 — COMMENTED** [review]
Great work!

**Pull request merged**
